services:
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:5000"

  # db:
    # image: postgres

  redis:
    image: "redis:alpine"
